# -*- coding: utf-8 -*-
"""Inference on CausalLM.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xmgb9Al015ATMSgqcyxDLJH59cxIHH26
"""

!pip install transformers
!pip install sentencepiece
!pip install datasets

from transformers import AutoTokenizer, AutoModelForCausalLM, FillMaskPipeline
import torch
from torch.utils.data import random_split
from datasets import load_dataset

model = AutoModelForCausalLM.from_pretrained('facebook/mbart-large-50')
tokenizer = AutoTokenizer.from_pretrained('facebook/mbart-large-50',src_lang='en_XX',tgt_lang='en_XX')

dataset = load_dataset('wikitext','wikitext-103-raw-v1')

temp = dataset['test'][3]['text'].split('.')
temp

input = tokenizer(temp[0],return_tensors='pt')
input

input['label'] = input.input_ids.detach().clone()

input['label'][0][3] = 103

input['label'][0]

pipeline = FillMaskPipeline(model=model,tokenizer=tokenizer,top_k=10)

pipeline('Robert Boulter is an English film , <mask> and theatre actor')

